name: CI
on:
  push:
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: liberica
          java-version: 17

      - name: Build
        run: make snapshot

      - uses: actions/upload-artifact@master
        with:
          name: spring-app
          path: build/libs

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: spring-app
          path: build/libs

      - name: Build Docker
        run: make start

      - name: Shutdown Docker
        run: make stop
